[package]
name = "vk-bot"
version = "0.1.0"
authors = ["Artem Varaksa <aymfst@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
serde = "1.0.84"
serde_json = "1.0.38"
serde_derive = "1.0.84"
log = "0.4"
simple_logger = "1.0.1"
rvk = "0.9.1"
regex = "1.1.0"
